import { Container } from '@mui/material'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { type Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export type LayoutProps = {
  children: React.ReactNode
}

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <body className={inter.className}>
          <Container maxWidth="md">{children}</Container>
        </body>
      </AppRouterCacheProvider>
    </html>
  )
}
export default RootLayout
